apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  db.yaml: bWFzdGVyOgogIGhvc3Q6ICdwZ3Bvb2wtc3ZjJwogIHBvcnQ6ICczMzA2JwogIG5hbWU6ICdhY2NvdW50cycKICB1c2VyOiAnYWNjb3VudHMnCiAgcGFzczogJ2VyRGcmcVdDMWZhaE9PaU0jOUNGemRoUzFkTCEqSXInCg==