package option

const (
    CREATE_CHARACTER = "CREATE_CHARACTER"

    UPDATE_CHARACTER     = "UPDATE_CHARACTER"
    UPDATE_CHARACTER_ANY = "UPDATE_CHARACTER_ANY"

    DELETE_CHARACTER     = "DELETE_CHARACTER"
    DELETE_CHARACTER_ANY = "DELETE_CHARACTER_ANY"

    LIST_CHARACTERS     = "LIST_CHARACTERS"
    LIST_CHARACTERS_ANY = "LIST_CHARACTERS_ANY"

    GET_CHARACTER     = "GET_CHARACTERS"
    GET_CHARACTER_ANY = "GET_CHARACTERS_ANY"
)
